env_name: 'SlipperyAnt-v3'
act_type: 'ReLU'
n_steps: 2e7
change_time: 2000000
g: 0.99
lm: 0.95
u_epi_ups: 0
bs: 2048
n_itrs: 10
n_slices: 16
lr: 0.0001
h_dim: [256, 256]
u_adv_scl: 1
clip_eps: 0.2
ob_norm: 0
rew_norm: 0
beta_1: 0.99
beta_2: 0.99
wd: 1e-4
use_er: true
er_lr: 0.000004
er_batch: 256
er_step: 1
frictions_file: 'cfg/frictions'
to_log: ['pol_features_activity', 'pol_weights', 'val_weights', 'stable_rank', 'dead_neurons', 'effective_rank']
dir: 'data/sant/l2_er/'
label: 'PPO+L2+ER'